version: "3.5"
services:
  portainer:
    image: portainer/portainer-ce:2.16.2-alpine
    ports:
      - 9001:9443 # HTTPS
      - 9002:9000 # HTTP
    volumes:
    # for linux
       # - data:/data
       # - /var/run/docker.sock:/var/run/docker.sock
    # for windows
      - C:\Docker_data\portainer:/data
      - C:\Docker_data\portainer:/var/run/docker.sock
    restart: unless-stopped
    
volumes:
  data:
