version: '3'
services:

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.9
    ports:
      - "4440:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - selenoid
    depends_on:
      - selenoid
      
  selenoid:
    image: aerokube/selenoid:1.10.9
    volumes:
      - C:\Docker_data\selenoid\config:/etc/selenoid
      - C:\Docker_data\selenoid\sock:/var/run/docker.sock
      - C:\Docker_data\selenoid\video:/opt/selenoid/video
      - C:\Docker_data\selenoid\logs:/opt/selenoid/logs
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    networks:
      - selenoid
    ports:
      - "4444:4444"

    
networks:
  selenoid:
    driver: bridge
